name: Lint (ESLint and Prettier)
# from: https://github.com/wearerequired/lint-action

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Build and Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./siloam
        run: npm ci

      # - name: Run linters
      #   uses: rkuykendall/lint-action@master
      #   with:
      #     eslint_dir: siloam/
      #     prettier_dir: siloam/
      #     eslint: true
      #     prettier: true

      - name: Run the build
        working-directory: ./siloam
        run: npm run build
